directories:
  output: release
  buildResources: build
appId: com.worktoper.agentos
productName: WorkToper Agent OS
copyright: Copyright © 2026 WorkToper
files:
  - filter:
      - '!node_modules/**/*'
      - desktop/**/*
      - images/icons/icon.png
      - out/**/*
      - package.json
icon: images/icons/icon.png
compression: maximum
toolsets:
  appimage: 1.0.3
electronLanguages:
  - en-US
  - zh-CN
  - zh_CN
npmRebuild: false
afterPack: scripts/after-pack.cjs
extraResources:
  - from: images/bg
    to: images/bg
    filter:
      - '**/*'
asar: true
mac:
  category: public.app-category.developer-tools
  icon: images/icons/icon.icns
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.inherit.plist
  extraResources:
    - from: runtime/qemu/darwin
      to: runtime/qemu/darwin
    - from: runtime/tools/darwin
      to: runtime/tools/darwin
  target:
    - dmg
    - zip
win:
  icon: images/icons/icon.ico
  extraResources:
    - from: runtime/qemu/win32
      to: runtime/qemu/win32
    - from: runtime/tools/win32
      to: runtime/tools/win32
  target:
    - nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: always
  createStartMenuShortcut: true
  shortcutName: WorkToper Agent OS
  installerIcon: images/icons/icon.ico
  uninstallerIcon: images/icons/icon.ico
linux:
  category: Development
  icon: images/icons/icons
  maintainer: WorkToper <support@worktoper.com>
  syncDesktopName: true
  extraResources:
    - from: runtime/qemu/linux
      to: runtime/qemu/linux
    - from: runtime/tools/linux
      to: runtime/tools/linux
  target:
    - AppImage
    - deb
electronDist: runtime/electron
electronVersion: 43.3.0
